[advisories]
ignore = [
    "RUSTSEC-2024-0436"
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Zlib",
    "ISC",
    "NCSA",
    "CC0-1.0",
    "BSL-1.0",
    "BSD-3-Clause",
    "BSD-2-Clause"
]
confidence-threshold = 0.8

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
